# Generated by Django 4.2.19 on 2025-02-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('qarz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passport', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('ijro_raqami', models.CharField(max_length=14)),
                ('mazmuni', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.debitor')),
            ],
        ),
    ]
