# Generated by Django 4.2.19 on 2025-02-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitorSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ijro_ish_raqami', models.CharField(max_length=50)),
                ('ijro_hujjat_raqami', models.CharField(max_length=50)),
                ('ijro_hujjat_mazmuni', models.TextField()),
                ('ijro_hujjat_summasi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qarzdor_fish', models.CharField(max_length=255)),
                ('telefon_raqami', models.CharField(blank=True, max_length=20, null=True)),
                ('operator_fish', models.CharField(blank=True, max_length=255, null=True)),
                ('operator_telefon_raqami', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
