# Generated by Django 4.2.19 on 2025-02-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_debitorsms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitorSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ijro_ish_raqami', models.CharField(max_length=255, unique=True, verbose_name='Ijro Ish Raqami')),
                ('ijro_hujjat_raqami', models.CharField(max_length=255, verbose_name='Ijro Hujjat Raqami')),
                ('ijro_hujjat_mazmuni', models.CharField(max_length=500, verbose_name='Ijro Hujjat Mazmuni')),
                ('ijro_hujjat_summasi', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ijro Hujjati Summasi')),
                ('qarzdor_fish', models.CharField(max_length=255, verbose_name='Qarzdor F.I.SH')),
                ('telefon_raqami', models.CharField(max_length=20, verbose_name='Telefon Raqami')),
                ('operator_fish', models.CharField(max_length=255, verbose_name='Operator F.I.SH')),
                ('operator_telefon_raqami', models.CharField(max_length=20, verbose_name='Operator Telefon Raqami')),
                ('sms_text', models.TextField(blank=True, null=True, verbose_name='Yaratilgan SMS Matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
            ],
        ),
    ]
