# Generated by Django 4.2.19 on 2025-02-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_debitorusi_debitorsendusi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitorSendGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('DebitorSms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.debitorsms')),
            ],
        ),
    ]
