# Generated by Django 4.2.19 on 2025-02-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_debitorsendget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitorsendget',
            old_name='DebitorSms',
            new_name='debitor_sms',
        ),
    ]
