# Generated by Django 4.2.19 on 2025-02-28 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_rename_debitorsms_debitorsendget_debitor_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitorSendGetSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon_raqami', models.CharField(max_length=20)),
                ('sms_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debitor_sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.debitorsms')),
            ],
        ),
    ]
